from __future__ import annotations

import json
import os
import shlex
from pathlib import Path
from typing import Any


def geoclaw_home() -> Path:
    override = os.environ.get("GEOCLAW_OPENAI_HOME", "").strip()
    if override:
        return Path(override).expanduser().resolve()
    return Path.home() / ".geoclaw-openai"


def config_path() -> Path:
    return geoclaw_home() / "config.json"


def env_path() -> Path:
    return geoclaw_home() / ".env"


def env_sh_path() -> Path:
    return geoclaw_home() / "env.sh"


def ensure_home() -> Path:
    home = geoclaw_home()
    home.mkdir(parents=True, exist_ok=True)
    return home


def detect_qgis_process(explicit: str = "") -> str:
    if explicit:
        p = Path(explicit).expanduser()
        if p.exists() and p.is_file():
            return str(p.resolve())
        raise FileNotFoundError(f"qgis_process not found at {explicit}")

    env_qp = os.environ.get("GEOCLAW_OPENAI_QGIS_PROCESS", "").strip()
    if env_qp:
        p = Path(env_qp)
        if p.exists() and p.is_file():
            return str(p)

    candidates = [
        "qgis_process",
        "/Applications/QGIS.app/Contents/MacOS/bin/qgis_process",
        "/Applications/QGIS-LTR.app/Contents/MacOS/bin/qgis_process",
    ]
    for candidate in candidates:
        if "/" in candidate:
            p = Path(candidate)
            if p.exists() and p.is_file():
                return str(p)
        else:
            from shutil import which

            found = which(candidate)
            if found:
                return found
    return ""


def read_config() -> dict[str, Any]:
    path = config_path()
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if isinstance(payload, dict):
        return payload
    return {}


def write_config(payload: dict[str, Any]) -> Path:
    ensure_home()
    path = config_path()
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if value and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key] = value
    return values


def write_env(values: dict[str, str]) -> Path:
    ensure_home()
    path = env_path()
    lines = ["# GeoClaw runtime environment\n"]
    for key in sorted(values.keys()):
        lines.append(f"{key}={values[key]}\n")
    path.write_text("".join(lines), encoding="utf-8")
    os.chmod(path, 0o600)
    return path


def write_env_sh(values: dict[str, str]) -> Path:
    ensure_home()
    path = env_sh_path()
    lines = ["#!/usr/bin/env bash\n", "# Generated by geoclaw-openai onboard\n"]
    for key in sorted(values.keys()):
        lines.append(f"export {key}={shlex.quote(values[key])}\n")
    path.write_text("".join(lines), encoding="utf-8")
    os.chmod(path, 0o700)
    return path


def bootstrap_runtime_env(override: bool = False) -> dict[str, str]:
    values = parse_env_file(env_path())
    for key, value in values.items():
        if override or key not in os.environ:
            os.environ[key] = value
    return values
